using Microsoft.CodeAnalysis;
using System.Text;

namespace SourceGenDemo.Generators;

[Generator]
public class HelloWorldGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(Emit);

    private void Emit(IncrementalGeneratorPostInitializationContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();

        sb.AppendLine("public static class Hello");
        sb.AppendLine("{");
        sb.AppendLine("    public static string World => \"Hello World!\";");
        sb.AppendLine("}");

        context.AddSource("HelloWorld.g.cs", sb.ToString());
    }
}
