//HintName: CqrsDependencyInjection.g.cs
// <auto-generated />

using Microsoft.Extensions.DependencyInjection;

public static class CqrsDependencyInjection
{
    public static void AddCqrs(this IServiceCollection services)
    {
        services.AddScoped<IRequestHandler<TestQuery, string>, TestQueryHandler>();
    }
}
